function [ReturnFn] = Electrify_Scenario_ReturnFn_Setup(scenario,vfoptions)

ReturnFn=struct('household', [], 'firm', [], 'energy', []);

% Hardwire buyhouse, hprime, aprime, h, a, and solarpv to zero
ReturnFn_12.household=@( ...
    labor,saprime,sa,z,e, ...
    pension,AccidentBeqS,w,P0,D, ...
    sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last,warmglow1,warmglow2,ypp,agej,Jr,J,...
    scenario,r,r_wedge,minhouse,rentprice,houseservices,energy_pct_cost ...
) Electrify_HouseholdReturnFn( ...
    labor,0,saprime,0,sa,0,0,z,e, ...
    pension,AccidentBeqS,0,w,P0,D, ...
    sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last,warmglow1,warmglow2,ypp,agej,Jr,J,...
    scenario,r,r_wedge,0,minhouse,rentprice,0,houseservices,0,0,energy_pct_cost ...
);
% Notice we use 'Electrify_HouseholdReturnFn'
ReturnFn_3.household=@( ...
        labor,buyhouse,saprime,hprime,sa,h,solarpv,z,e, ...
        pension,AccidentBeqS,AccidentBeqAH,w,P0,D, ...
        sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last,warmglow1,warmglow2,ypp,agej,Jr,J,...
        scenario,r,r_wedge,f_htc,minhouse,rentprice,f_coll,houseservices,cpi,pv_pct_cost,energy_pct_cost ...
    ) Electrify_HouseholdReturnFn( ...
        labor,buyhouse,saprime,hprime,sa,h,solarpv,z,e, ...
        pension,AccidentBeqS,AccidentBeqAH,w,P0,D, ...
        sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last,warmglow1,warmglow2,ypp,agej,Jr,J,...
        scenario,r,r_wedge,f_htc,minhouse,rentprice,f_coll,houseservices,cpi,pv_pct_cost,energy_pct_cost ...
    );
if strcmp(vfoptions.precision.household,'single')
    ReturnFn_4.household=@( ...
        labor,buyhouse,saprime,cprime,hprime,sa,car,h,solarpv,z,e, ...
        pension,AccidentBeqS,AccidentBeqAH,w,P0,D,sigma,psi,eta,sigma_h,sigma_c,kappa_j,warmglow1,warmglow2,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
        ypp,agej,Jr,J,r,r_wedge,f_htc,minhouse,rentprice,f_coll,houseservices,carservices_j,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
        ) Electrify_4HouseholdReturnFn_single( ...
        labor,buyhouse,saprime,cprime,hprime,sa,car,h,solarpv,z,e, ...
        pension,AccidentBeqS,AccidentBeqAH,w,P0,D,sigma,psi,eta,sigma_h,sigma_c,kappa_j,warmglow1,warmglow2,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
        ypp,agej,Jr,J,r,r_wedge,f_htc,minhouse,rentprice,f_coll,houseservices,carservices_j,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
        );
else
    ReturnFn_4.household=@( ...
            labor,buyhouse,saprime,cprime,hprime,sa,car,h,solarpv,z,e, ...
            pension,AccidentBeqS,AccidentBeqAH,w,P0,D,sigma,psi,eta,sigma_h,sigma_c,kappa_j,warmglow1,warmglow2,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
            ypp,agej,Jr,J,r,r_wedge,f_htc,minhouse,rentprice,f_coll,houseservices,carservices_j,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
        ) Electrify_4HouseholdReturnFn( ...
            labor,buyhouse,saprime,cprime,hprime,sa,car,h,solarpv,z,e, ...
            pension,AccidentBeqS,AccidentBeqAH,w,P0,D,sigma,psi,eta,sigma_h,sigma_c,kappa_j,warmglow1,warmglow2,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
            ypp,agej,Jr,J,r,r_wedge,f_htc,minhouse,rentprice,f_coll,houseservices,carservices_j,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
        );
end

if scenario<3
    ReturnFn.household=ReturnFn_12.household;
elseif scenario<4
    ReturnFn.household=ReturnFn_3.household;
else
    ReturnFn.household=ReturnFn_4.household;
end

% Notice we use 'Electrify_FirmReturnFn'
ReturnFn_123.firm=@( ...
        d,kprime,k,z, ...
        w, D, ...
        ypp,delta,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg ...
    ) Electrify_FirmReturnFn( ...
        d,kprime,k,z, ...
        w, D, ...
        ypp,delta,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg ...
    );
% Notice we use 'Electrify_4FirmReturnFn'
ReturnFn_4.firm=@( ...
        pvnew,kprime,k,pv,z, ...
        w, ...
        ypp,pvinstalled_firm,pvmax_firm,delta,pv_delta,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg,Ek,ek,energy_pct_brown,carbon_tax ...
    ) Electrify_4FirmReturnFn( ...
        pvnew,kprime,k,pv,z, ...
        w, ...
        ypp,pvinstalled_firm,pvmax_firm,delta,pv_delta,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg,Ek,ek,energy_pct_brown,carbon_tax ...
    );

if scenario<4
    ReturnFn.firm=ReturnFn_123.firm;
else
    ReturnFn.firm=ReturnFn_4.firm;
end

% Notice we use 'Electrify_EnergyReturnFn'
ReturnFn_123.energy=@( ...
        aprime,a,z ...
    ) Electrify_EnergyReturnFn( ...
        aprime,a,z ...
    );
% Notice we use 'Electrify_4EnergyReturnFn'
ReturnFn_4.energy=@( ...
        pvnew,kprime,k,pv,z, ...
        ypp,pvinstalled_energy,pvmax_energy,delta,pv_delta,EnergyCosts_h,EnergyCosts_f ...
    ) Electrify_4EnergyReturnFn( ...
        pvnew,kprime,k,pv,z, ...
        ypp,pvinstalled_energy,pvmax_energy,delta,pv_delta,EnergyCosts_h,EnergyCosts_f ...
    );

if scenario<4
    ReturnFn.energy=ReturnFn_123.energy;
else
    ReturnFn.energy=ReturnFn_4.energy;
end


end
