function F = ElectrifyHousingsemizV_ReturnFn_single(installpv, buyhouse, aprime, hprime, a, h, solarpv, ...
    pbefore, pafter, yearsowned, olddownpayment, z, ...
    w, r, sigma, agej, Jr, pension, kappa_j, sigma_h, f_htc, minhouse, rentprice, houseservices, mortgageduration, pv_pct_cost, energy_pct_cost)

    % Deploy the wave! 
    % MATLAB will compile CoreMath_single into a native CUDA kernel and broadcast the tensors.
    F = arrayfun(@ElectrifyHousing_CoreMath_single, ...
        installpv, buyhouse, aprime, hprime, a, h, solarpv, ...
        pbefore, pafter, yearsowned, olddownpayment, z, ...
        w, r, sigma, agej, Jr, pension, kappa_j, sigma_h, f_htc, minhouse, rentprice, houseservices, mortgageduration, pv_pct_cost, energy_pct_cost);

end