function [ReturnFn,FnsToEvaluate,FnsToEvaluate2,FnsToEvaluate3,vfoptions,simoptions] = Electrify_Scenario_Fn_Setup(Params,vfoptions,simoptions)

ReturnFn=Electrify_Scenario_ReturnFn_Setup(Params.scenario);

% We return the aprime functions in vfoptions and simoptions


%% Define aprime function used for the experience asset

% experienceasset: aprime_val=aprimeFn(d,a)
% vfoptions.refine_d: the decision variables input to aprimeFn are d3
aprimeFn.household=@(buyhouse, solarpv, pv_delta_pp) ElectrifyHousing_aprimeFn(buyhouse, solarpv, pv_delta_pp); % Will return the value of aprime (solarpv)
aprimeFn.firm=@(pvnew, pv, ypp,pvinstalled_firm,pvmax_firm,pv_delta_pp) ElectrifyFirm_aprimeFn(pvnew, pv, ypp,pvinstalled_firm,pvmax_firm,pv_delta_pp); % Will return the value of aprime (solarpv)
aprimeFn.energy=@(pvnew, pv, ypp,pvinstalled_firm,pvmax_firm,pv_delta_pp) ElectrifyEnergy_aprimeFn(pvnew, pv, ypp,pvinstalled_firm,pvmax_firm,pv_delta_pp); % Will return the value of aprime (solarpv)

%% Put aprimeFns into vfoptions and simoptions (household, firm, and energy)
vfoptions.aprimeFn=aprimeFn;
simoptions.aprimeFn=aprimeFn;
% experienceasset: aprime_val=aprimeFn(d,a)

% Stationary Distribution Aggregates from households (important that ordering of Names and Functions is the same)
FnsToEvaluate_12.L_h.household=@(labor,sprime,s,z,e,kappa_j,Lhscale) ...
    labor*kappa_j*exp(z+e)*Lhscale;  % Aggregate labour supply in efficiency units, not scaled by ypp
FnsToEvaluate_12.S.household=@(labor,sprime,s,z,e) s; % Aggregate share holdings
FnsToEvaluate_12.PensionSpending.household=@(labor,sprime,s,z,e,pension,ypp,agej,Jr) ...
    (agej>=Jr)*pension; % Total spending on pensions
FnsToEvaluate_12.PayrollTaxRevenue.household=@(labor,sprime,s,z,e,ypp,agej,Jr,tau_l,w,kappa_j,Lhscale) ...
    (agej<Jr)*tau_l*labor*w*kappa_j*exp(z+e); % Total spending on payroll taxes
FnsToEvaluate_12.CapitalGainsTaxRevenue.household=@(labor,sprime,s,z,e,tau_cg,P0,D_pp,tau_d,r_pp) ...
    tau_cg*(P0-(((1-tau_cg)*P0 + (1-tau_d)*D_pp)/(1+r_pp-tau_cg)))*s; % tau_cg*(P0-Plag)*s, but substitute P=Plag, and then substitute for P
FnsToEvaluate_12.BeqleftS_pp.household=@(labor,sprime,s,z,e,sj) ...
    sprime*(1-sj); % Accidental share bequests left by people who die
FnsToEvaluate_3.L_h.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,kappa_j,Lhscale) ...
    labor*kappa_j*exp(z+e)*Lhscale;  % Aggregate labour supply in efficiency units, not scaled by ypp
FnsToEvaluate_3.S.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e) s; % Aggregate share holdings
FnsToEvaluate_3.PensionSpending.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,pension,ypp,agej,Jr) ...
    (agej>=Jr)*pension; % Total spending on pensions
FnsToEvaluate_3.PayrollTaxRevenue.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,ypp,agej,Jr,tau_l,w,kappa_j,Lhscale) ...
    (agej<Jr)*tau_l*labor*w*kappa_j*exp(z+e); % Total spending on payroll taxes
FnsToEvaluate_3.CapitalGainsTaxRevenue.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,tau_cg,P0,D_pp,tau_d,r_pp) ...
    tau_cg*(P0-(((1-tau_cg)*P0 + (1-tau_d)*D_pp)/(1+r_pp-tau_cg)))*s+(1-tau_d)*r_pp*max(a,0); % tau_cg*(P0-Plag)*s + deposit interest, but substitute P=Plag, and then substitute for P
FnsToEvaluate_3.BeqleftS_pp.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,sj) ...
    sprime*(1-sj); % Accidental share bequests left by people who die
% AccidentalBeqAHLeft is zero (if in debt) or accidental asset+house bequests left by people who die
FnsToEvaluate_3.BeqleftAH_pp.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,scenario,sj,cpi) ...
    max(0,(aprime+(1+cpi)*hprime)*(1-sj));
% BadDebt is the debt somebody accidentally leaves behind, or zero if net worth is positive
FnsToEvaluate_4.L_h.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,kappa_j,Lhscale) ...
    labor*kappa_j*exp(z+e)*Lhscale;  % Aggregate labour supply in efficiency units, not scaled by ypp
FnsToEvaluate_4.S.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e) s; % Aggregate share holdings
FnsToEvaluate_4.PensionSpending.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,pension,ypp,agej,Jr) ...
    (agej>=Jr)*pension; % Total spending on pensions
FnsToEvaluate_4.PayrollTaxRevenue.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,ypp,agej,Jr,tau_l,w,kappa_j,Lhscale) ...
    (agej<Jr)*tau_l*labor*w*kappa_j*exp(z+e); % Total spending on payroll taxes
FnsToEvaluate_4.CapitalGainsTaxRevenue.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,ypp,agej,P0,AccidentBeqS_pp,r_pp,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last) ...
    Electrify_4HouseholdCapitalGainsFn(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,ypp,agej,0,P0,AccidentBeqS_pp,r_pp,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last);
FnsToEvaluate_4.BeqleftS_pp.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,sj,n_pp,ypp,agej,P0,AccidentBeqS_pp,r_pp,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last) ... % Accidental bequests left by people who die, (possibly after estate taxes) and dilution to dependents
    (sprime-Electrify_4HouseholdCapitalGainsFn(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,ypp,agej,1,P0,AccidentBeqS_pp,r_pp,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last))*(1-sj)/(1+n_pp);

% AccidentalBeqAHLeft is zero (if in debt) or accidental asset+house bequests left by people who die
FnsToEvaluate_4.BeqleftAH_pp.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,scenario,sj,cpi) ...
    max(0,(aprime+(1+cpi)*hprime)*(1-sj));
% BadDebt is the debt somebody accidentally leaves behind, or zero if net worth is positive
FnsToEvaluate_4.EnergyCosts_h.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,w,ypp,cpi_energy,energy_pct_cost) ...
    Electrify_4HouseholdEnergyCosts(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,w,ypp,cpi_energy,energy_pct_cost);
FnsToEvaluate_4.CarbonCosts_h.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,w,ypp,cpi_energy,energy_pct_cost,energy_pct_brown,carbon_tax) ...
    Electrify_4HouseholdCarbonCosts(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,w,ypp,cpi_energy,energy_pct_cost,energy_pct_brown,carbon_tax);

% From firms
FnsToEvaluate_12.L_f.firm=@(d,kprime,k,z,w,alpha_k,alpha_l) ...
    (w/(alpha_l*z*(k^alpha_k)))^(1/(alpha_l-1)); % (effective units of) labor demanded by firm, not scaled by ypp
FnsToEvaluate_12.K.firm=@(d,kprime,k,z) k; % physical capital
FnsToEvaluate_12.dividend_pp.firm=@(d,kprime,k,z,ypp) (1+d)^ypp-1; % dividend paid by firm
FnsToEvaluate_12.Sissued.firm=@(d,kprime,k,z,w,ypp,delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi) ...
    Electrify_FirmShareIssuance(d,kprime,k,z,w,ypp,delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi); % Share issuance
FnsToEvaluate_12.CorpTaxRevenue.firm=@(d,kprime,k,z,w,ypp,delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi) ...
    Electrify_FirmCorporateTaxRevenue(d,kprime,k,z,w,ypp,delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi); % revenue from the corporate profits tax
fnnames=fieldnames(FnsToEvaluate_12);
for ff=1:length(fnnames)
    if isfield(FnsToEvaluate_12.(fnnames{ff}), 'firm')
        FnsToEvaluate_3.(fnnames{ff}).firm=FnsToEvaluate_12.(fnnames{ff}).firm;
    end
end
FnsToEvaluate_4.L_f.firm=@(pvnew,kprime,k,pv,z,w,alpha_k,alpha_l) ...
    (w/(alpha_l*z*(k^alpha_k)))^(1/(alpha_l-1)); % (effective units of) labor demanded by firm, not scaled by ypp
FnsToEvaluate_4.K.firm=@(pvnew,kprime,k,pv,z) k; % physical capital
FnsToEvaluate_4.pvnew_f.firm=@(pvnew,kprime,k,pv,z,pvinstalled_firm,pvmax_firm) pvnew;
FnsToEvaluate_4.pv_f.firm=@(pvnew,kprime,k,pv,z,pvinstalled_firm,pvmax_firm) pv;
FnsToEvaluate_4.D_pp.firm=@(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,Ek,ek,energy_pct_brown,carbon_tax) ...
    Electrify_4FirmDividend(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,Ek,ek,energy_pct_brown,carbon_tax); % dividend paid by firm
FnsToEvaluate_4.Sissued.firm=@(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,Ek,ek,energy_pct_brown,carbon_tax) ...
    Electrify_4FirmShareIssuance(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,Ek,ek,energy_pct_brown,carbon_tax); % Share issuance
FnsToEvaluate_4.CorpTaxRevenue.firm=@(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,Ek,ek,energy_pct_brown,carbon_tax) ...
    Electrify_4FirmCorporateTaxRevenue(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,Ek,ek,energy_pct_brown,carbon_tax); % revenue from the corporate profits tax
FnsToEvaluate_4.EnergyCosts_f.firm=@(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,Ek,ek,carbon_tax) ...
    Electrify_4FirmEnergyCosts(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,Ek,ek,carbon_tax);
FnsToEvaluate_4.CarbonCosts_f.firm=@(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,Ek,ek,energy_pct_brown,carbon_tax) ...
    Electrify_4FirmCarbonCosts(pvnew,kprime,k,pv,z,w,ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,Ek,ek,energy_pct_brown,carbon_tax);

% From energy -- there must be at least one
FnsToEvaluate_12.EnergyRevenue.energy=@(aprime,a,z) 0;
FnsToEvaluate_3.EnergyRevenue.energy=@(aprime,a,z) 0;
FnsToEvaluate_4.EnergyRevenue.energy=@(invest,aprime,a,z,EnergyCosts_h,EnergyCosts_f) EnergyCosts_h+EnergyCosts_f;
FnsToEvaluate_4.TransitionInvestment.energy=@(invest,aprime,a,z,CarbonCosts_h,CarbonCosts_f) CarbonCosts_h+CarbonCosts_f;
FnsToEvaluate_4.pvnew_e.energy=@(pvnew,kprime,k,pv,z,pvinstalled_firm,pvmax_energy) pvnew;
FnsToEvaluate_4.pv_e.energy=@(pvnew,kprime,k,pv,z,pvinstalled_firm,pvmax_energy) pv;

% For analysing the model
FnsToEvaluate2_12=FnsToEvaluate_12;
FnsToEvaluate2_12.earnings.household=@(labor,aprime,a,z,e,w,kappa_j,Lhscale) w*kappa_j*labor*exp(z+e)*Lhscale; % w*kappa_j is the labor earnings
FnsToEvaluate2_3=FnsToEvaluate_3;
FnsToEvaluate2_3.earnings.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,w,kappa_j,Lhscale) w*kappa_j*labor*exp(z+e)*Lhscale; % w*kappa_j is the labor earnings
FnsToEvaluate2_3.A.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e) a; % Aggregate share holdings
FnsToEvaluate2_3.H.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e) h; % Aggregate house holdings
FnsToEvaluate2_3.PV_h.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e) solarpv; % Aggregate solarpv holdings
FnsToEvaluate2_3.BadDebt_pp.household=@(labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e,scenario,sj,cpi) ...
    min(0,(aprime+(1+cpi)*hprime)*(1-sj));
FnsToEvaluate2_4=FnsToEvaluate_4;
FnsToEvaluate2_4.earnings.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,w,kappa_j,Lhscale) w*kappa_j*labor*exp(z+e)*Lhscale; % w*kappa_j is the labor earnings
FnsToEvaluate2_4.Car.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e) car; % Aggregate house holdings
FnsToEvaluate2_4.A.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e) a; % Aggregate asset/mortgage holdings
FnsToEvaluate2_4.H.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e) h; % Aggregate house holdings
FnsToEvaluate2_4.PV_h.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e) solarpv; % Aggregate solarpv holdings
FnsToEvaluate2_4.BadDebt_pp.household=@(labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e,scenario,sj,cpi) ...
    min(0,(aprime+(1+cpi)*hprime)*(1-sj));

% Note: I keep the FnsToEvaluate use in general eqm to a minimum (to reduce
% runtimes) and then use FnsToEvaluate2 to analyse model with more stats.
% Note: FnsToEvaluate may need 'e' grids, but AggVars and other stats use a
% a joint ze grid (which reads as z in their parameter lists).
if Params.scenario<3
    FnsToEvaluate=FnsToEvaluate_12;
    FnsToEvaluate2=FnsToEvaluate2_12;
elseif Params.scenario<4
    FnsToEvaluate=FnsToEvaluate_3;
    FnsToEvaluate2=FnsToEvaluate2_3;
else
    FnsToEvaluate=FnsToEvaluate_4;
    FnsToEvaluate2=FnsToEvaluate2_4;
end

FnsToEvaluate3=FnsToEvaluate2;
% Add consumption, income, and output to FnsToEvaluate3
if Params.scenario<3
    FnsToEvaluate3.Consumption.household=@( ...
            labor,sprime,s,z,e, ...
            pension,AccidentBeqS_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,cpi,rentprice,energy_pct_cost ...
        ) Electrify_HouseholdConsumptionFn( ...
            labor,0,sprime,0,0,s,0,0,0,z,e, ...
            pension,AccidentBeqS_pp,0,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,0,cpi,rentprice,0,0,energy_pct_cost);
    FnsToEvaluate3.Income.household=@( ...
            labor,sprime,s,z,e, ...
            pension,AccidentBeqS_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,cpi,energy_pct_cost ...
        ) Electrify_HouseholdIncomeFn( ...
            labor,0,sprime,0,0,s,0,0,0,z,e, ...
            pension,AccidentBeqS_pp,0,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,cpi,energy_pct_cost);
    FnsToEvaluate3.Output_f.firm=@(d,kprime,k,z,w,alpha_k,alpha_l) ...
       z*(k^alpha_k)*((w/(alpha_l*z*(k^alpha_k)))^(1/(alpha_l-1)))^alpha_l; % Production function z*(k^alpha_k)*(l^alpha_l) (substituting for l)
elseif Params.scenario<4
    FnsToEvaluate3.Consumption.household=@( ...
            labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,r_wedge_pp,f_htc,rentprice,cpi_energy,pv_pct_cost,energy_pct_cost ...
        ) Electrify_HouseholdConsumptionFn( ...
            labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,r_wedge_pp,f_htc,rentprice,cpi_energy,pv_pct_cost,energy_pct_cost);
    FnsToEvaluate3.Income.household=@( ...
            labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,cpi_energy,energy_pct_cost ...
        ) Electrify_HouseholdIncomeFn( ...
            labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,ypp,agej,Jr, ...
            r_pp,cpi_energy,energy_pct_cost);
    FnsToEvaluate3.Output_f.firm=@(d,kprime,k,z,w,alpha_k,alpha_l) ...
       z*(k^alpha_k)*((w/(alpha_l*z*(k^alpha_k)))^(1/(alpha_l-1)))^alpha_l; % Production function z*(k^alpha_k)*(l^alpha_l) (substituting for l)
else
    FnsToEvaluate3.Consumption.household=@( ...
            labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
            ypp,agej,Jr,r_pp,r_wedge_pp,f_htc,rentprice,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
        ) Electrify_4HouseholdConsumptionFn( ...
            labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
            ypp,agej,Jr,r_pp,r_wedge_pp,f_htc,rentprice,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax);
    FnsToEvaluate3.Income.household=@( ...
            labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
            ypp,agej,Jr,r_pp,cpi_energy,energy_pct_cost,energy_pct_brown,carbon_tax ...
        ) Electrify_4HouseholdIncomeFn( ...
            labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e, ...
            pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
            kappa_j,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
            ypp,agej,Jr,r_pp,cpi_energy,energy_pct_cost,energy_pct_brown,carbon_tax);
    FnsToEvaluate3.Output_f.firm=@(pvnew,kprime,k,pv,z,w,alpha_k,alpha_l,Ek,ek) ...
        (Ek*ek)*z*(k^alpha_k)*((w/(alpha_l*z*(k^alpha_k)))^(1/(alpha_l-1)))^alpha_l; % Production function z*(k^alpha_k)*(l^alpha_l) (substituting for l)
end
    
end
