function [ReturnFn] = Electrify_Scenario_ReturnFn_Setup(scenario)

ReturnFn=struct('household', [], 'firm', [], 'energy', []);

% Hardwire buyhouse, hprime, aprime, h, a, and solarpv to zero
ReturnFn_12.household=@( ...
    labor,sprime,s,z,e, ...
    pension,AccidentBeqS_pp,w,P0,D_pp, ...
    sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,warmglow1,warmglow2,ypp,agej,Jr,J,...
    scenario,r_pp,r_wedge_pp,minhouse,rentprice,houseservices,energy_pct_cost ...
) Electrify_HouseholdReturnFn( ...
    labor,0,sprime,0,0,s,0,0,0,z,e, ...
    pension,AccidentBeqS_pp,0,w,P0,D_pp, ...
    sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,warmglow1,warmglow2,ypp,agej,Jr,J,...
    scenario,r_pp,r_wedge_pp,0,minhouse,rentprice,0,houseservices,0,0,energy_pct_cost ...
);
% Notice we use 'Electrify_HouseholdReturnFn'
ReturnFn_3.household=@( ...
        labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e, ...
        pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
        sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,warmglow1,warmglow2,ypp,agej,Jr,J,...
        scenario,r_pp,r_wedge_pp,f_htc,minhouse,rentprice,f_coll,houseservices,cpi,pv_pct_cost,energy_pct_cost ...
    ) Electrify_HouseholdReturnFn( ...
        labor,buyhouse,sprime,aprime,hprime,s,a,h,solarpv,z,e, ...
        pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp, ...
        sigma,psi,eta,sigma_h,kappa_j,tau_l,tau_d,tau_cg,warmglow1,warmglow2,ypp,agej,Jr,J,...
        scenario,r_pp,r_wedge_pp,f_htc,minhouse,rentprice,f_coll,houseservices,cpi,pv_pct_cost,energy_pct_cost ...
    );
ReturnFn_4.household=@( ...
        labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e, ...
        pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp,sigma,psi,eta,sigma_h,sigma_c,kappa_j,warmglow1,warmglow2,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
        ypp,agej,Jr,J,r_pp,r_wedge_pp,f_htc,minhouse,rentprice,f_coll,houseservices,carservices_j,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
    ) Electrify_4HouseholdReturnFn( ...
        labor,buyhouse,sprime,aprime,cprime,hprime,s,a,car,h,solarpv,z,e, ...
        pension,AccidentBeqS_pp,AccidentBeqAH_pp,w,P0,D_pp,sigma,psi,eta,sigma_h,sigma_c,kappa_j,warmglow1,warmglow2,tau_l,tau_d,tau_cg,S_agej_first,S_agej_peak_first,S_agej_peak_last,S_agej_last, ...
        ypp,agej,Jr,J,r_pp,r_wedge_pp,f_htc,minhouse,rentprice,f_coll,houseservices,carservices_j,cpi_energy,pv_pct_cost,energy_pct_cost,energy_pct_brown,carbon_tax ...
    );

if scenario<3
    ReturnFn.household=ReturnFn_12.household;
elseif scenario<4
    ReturnFn.household=ReturnFn_3.household;
else
    ReturnFn.household=ReturnFn_4.household;
end

% Notice we use 'Electrify_FirmReturnFn'
ReturnFn_123.firm=@( ...
        d,kprime,k,z, ...
        w, D_pp, ...
        ypp,delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg ...
    ) Electrify_FirmReturnFn( ...
        d,kprime,k,z, ...
        w, D_pp, ...
        ypp,delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg ...
    );
% Notice we use 'Electrify_4FirmReturnFn'
ReturnFn_4.firm=@( ...
        pvnew,kprime,k,pv,z, ...
        w, ...
        ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg,Ek,ek,energy_pct_brown,carbon_tax ...
    ) Electrify_4FirmReturnFn( ...
        pvnew,kprime,k,pv,z, ...
        w, ...
        ypp,pvinstalled_firm,pvmax_firm,delta_pp,pv_delta_pp,alpha_k,alpha_l,capadjconstant,tau_corp,phi,tau_d,tau_cg,Ek,ek,energy_pct_brown,carbon_tax ...
    );

if scenario<4
    ReturnFn.firm=ReturnFn_123.firm;
else
    ReturnFn.firm=ReturnFn_4.firm;
end

% Notice we use 'Electrify_EnergyReturnFn'
ReturnFn_123.energy=@( ...
        aprime,a,z ...
    ) Electrify_EnergyReturnFn( ...
        aprime,a,z ...
    );
% Notice we use 'Electrify_4EnergyReturnFn'
ReturnFn_4.energy=@( ...
        pvnew,kprime,k,pv,z, ...
        ypp,pvinstalled_energy,pvmax_energy,delta_pp,pv_delta_pp,EnergyCosts_h,EnergyCosts_f ...
    ) Electrify_4EnergyReturnFn( ...
        pvnew,kprime,k,pv,z, ...
        ypp,pvinstalled_energy,pvmax_energy,delta_pp,pv_delta_pp,EnergyCosts_h,EnergyCosts_f ...
    );

if scenario<4
    ReturnFn.energy=ReturnFn_123.energy;
else
    ReturnFn.energy=ReturnFn_4.energy;
end


end
